version: '3'

services:
  mango:
    container_name: mango
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "9393"
    ports:
      - "9393"
    volumes:
      - /media/hdd4/server/comics
      - ~/.config/mango
