version: '3'

services:
  mango:
    container_name: mango
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "9393"
    ports:
      - "9393"
    volumes:
      - ${MAIN_DIRECTORY_PATH}:/root/mango
      - ${CONFIG_DIRECTORY_PATH}:/root/.config/mango
